### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [xplrz/advanced-smart-contracting-template#1]
Target:

* [ ] Developer-oriented Makefile.
* [ ] Full CI/CD.
* [ ] Multi-contracts (dependencies) support, and examples.
* [ ] Contract versioning, and Proxy pattern support, and examples.
* [ ] Latest linters, with good configuration.
* [ ] Unit test examples (per-method, per file, support deps).
* [ ] Functional/E2E test examples (with versioning, and migration support).
* [ ] Localhost frontend development helpers (run a localhost webserver with etherjs, etc).
* [ ] README.md explaining the goal and particularities of this repo.
* [ ] Well documented (not necessarily the dummy contracts, but the rest).

Someday/Maybe:

* [ ] Multi blockchain support, `./solitidy/`, `./cosmwasm/`, `./cairo/`, `./gno/`...
* [ ] Functional/E2E cross-chain tests (i.e., atomic swap between two protocols).
* [ ] ZKRollup or other patterns helpers and examples.
* [ ] Better naming?
